"""
Django settings for stockbot project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

# LIBRARY IMPORTS
# ----------------------------------------------------------------------------------------

# Standard library imports
from os import environ

# Core django imports
from django.core.exceptions import ImproperlyConfigured

# Thrid party app imports
from unipath import Path

# Project imports

# ----------------------------------------------------------------------------------------




# ENVIRONMENT VARIABLES
# ----------------------------------------------------------------------------------------

def get_env_variable(key):
    """

    See: Two Scoops of Django 1.8 - Chapter 5, pg 52.

    Return the environment variable 'key' or raise an ImproperlyConfigured exception.
    @param key: name of the environment variable.

    """
    try:
    
        return environ[key]
    
    except KeyError:
    
        raise ImproperlyConfigured(
        
            'The environment variable {} does not exist.'.format(key)
        
        )

# ----------------------------------------------------------------------------------------




# ----------------------------------------------------------------------------------------

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^rt&cdvgp332e#&3yu!!l2om7*%-$@&28m_at7z9^z=tmi=bo-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# ----------------------------------------------------------------------------------------




# CONFIGURATION SETTINGS
# ----------------------------------------------------------------------------------------

ROOT_URLCONF = 'config.urls'

WSGI_APPLICATION = 'config.wsgi.application'

# ----------------------------------------------------------------------------------------




# DIRECTORIES
# ----------------------------------------------------------------------------------------

# Path to ulo/ relative to the position of this file: ulo/config/settings/base.py
BASE_DIR = Path(__file__).ancestor(3)

MEDIA_ROOT = BASE_DIR.child('media')

STATICFILES_DIRS = (BASE_DIR.child('static'),)

# ----------------------------------------------------------------------------------------




# URLS
# ----------------------------------------------------------------------------------------

MEDIA_URL = '/media/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
STATIC_URL = '/static/'

# ----------------------------------------------------------------------------------------




# APPLICATIONS
# ----------------------------------------------------------------------------------------

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'databases',
    'datasets',
    'stocks',

]

# ----------------------------------------------------------------------------------------




# MIDDLEWARE
# ----------------------------------------------------------------------------------------

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

# ----------------------------------------------------------------------------------------




# TEMPLATES
# ----------------------------------------------------------------------------------------

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': (BASE_DIR.child('templates'),),

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [
                
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'stockbot.context_processors.base_template',

            ],

        },

    },

]

# ----------------------------------------------------------------------------------------




# DATABASE
# ----------------------------------------------------------------------------------------

# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR.child('db.sqlite3'), # os.path.join(BASE_DIR, 'db.sqlite3'),

    }

}

# ----------------------------------------------------------------------------------------




# PASSWORD VALIDATION
# ----------------------------------------------------------------------------------------

# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ----------------------------------------------------------------------------------------




# INTERNATIONALISATION
# ----------------------------------------------------------------------------------------

# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# ----------------------------------------------------------------------------------------



